// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-h5jdcr0bxv996LoxZ5g0EeMRhJlPp2o',
    appId: '1:269879792675:web:fb50890cdd6ff8b5028d96',
    messagingSenderId: '269879792675',
    projectId: 'ecoscan-madrid',
    authDomain: 'ecoscan-madrid.firebaseapp.com',
    storageBucket: 'ecoscan-madrid.firebasestorage.app',
    databaseURL:
        'https://ecoscan-madrid-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcayBOGqAU8OUASe_seVkrVP1duG7b5pU',
    appId: '1:269879792675:android:d9caa9abc853d5b4028d96',
    messagingSenderId: '269879792675',
    projectId: 'ecoscan-madrid',
    storageBucket: 'ecoscan-madrid.firebasestorage.app',
    databaseURL:
        'https://ecoscan-madrid-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqMNGg41cLL8Ia-joI1OLnf3tkoO9Dlk',
    appId: '1:269879792675:ios:929538e36cb32a7c028d96',
    messagingSenderId: '269879792675',
    projectId: 'ecoscan-madrid',
    storageBucket: 'ecoscan-madrid.firebasestorage.app',
    databaseURL:
        'https://ecoscan-madrid-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGqMNGg41cLL8Ia-joI1OLnf3tkoO9Dlk',
    appId: '1:269879792675:ios:929538e36cb32a7c028d96',
    messagingSenderId: '269879792675',
    projectId: 'ecoscan-madrid',
    storageBucket: 'ecoscan-madrid.firebasestorage.app',
    databaseURL:
        'https://ecoscan-madrid-default-rtdb.europe-west1.firebasedatabase.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-h5jdcr0bxv996LoxZ5g0EeMRhJlPp2o',
    appId: '1:269879792675:web:49636bbc9f2ac517028d96',
    messagingSenderId: '269879792675',
    projectId: 'ecoscan-madrid',
    authDomain: 'ecoscan-madrid.firebaseapp.com',
    storageBucket: 'ecoscan-madrid.firebasestorage.app',
    databaseURL:
        'https://ecoscan-madrid-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
